backend:
  name: github
  repo: kevn1812/game
  branch: master

media_folder: "assets/images"
public_folder: "assets/images"

collections:
  - name: "games"
    label: "الألعاب"
    folder: "games"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "اسم اللعبة", name: "title", widget: "string"}
      - {label: "صورة اللعبة", name: "image", widget: "image"}
      - {label: "رابط التحميل", name: "link", widget: "string"}
      